version = 3
final_space = true
[palette]
  rosewater = "#F4DBD6"
  flamingo = "#F0C6C6"
  blue = "#8AADF4"
  red = "#ED8796"
  green = "#A6DA95"
  mauve = "#C6A0F6"
  yellow = "#EED49F"
  sky = "#91D7E3"
  sapphire = "#7DC4E4"
  lavender = "#B7BDF8"
  text = "#CAD3F5"
  base = "#24273A"
  pink = "#F5BDE6"
  maroon = "#EE99A0"
  peach = "#F5A97F"
  teal = "#8bd5ca"
  overlay0 = "#6E738D"
  surface0 = "#363A4F"
  mantle = "#1e2030"
  crust = "#181926"

[upgrade]
  source = "cdn"
  interval = "168h"
  auto = false
  notice = false

[[blocks]]
  type = "prompt"
  alignment = "left"
  
  [[blocks.segments]]
    type = "text"
    style = "plain"
    template = "\n"

  [[blocks.segments]]
    type = "nix-shell"
    background = "p:mauve"
    foreground = "p:mantle"
    template = "󱄅 {{ .Type }}"  
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""

  [[blocks.segments]]
    type = "session"
    foreground = "p:base"
    background = "p:rosewater"
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""
    template = "{{if .SSHSession}} {{end}}{{.UserName}}/{{.HostName}}"


  [[blocks.segments]]
    template = "["
    foreground = "p:blue"
    background = "transparent"
    type = "text"
    style="plain"

   [[blocks.segments]]
    type = "python"
    style = "diamond"
    leading_diamond = ""
    trailing_diamond = ""
    foreground = "p:mantle"
    background = "p:teal"
    template = " venv"

  [[blocks.segments]]
    type = "project"
    style = "powerline"
    foreground = "p:blue"
    background = "transparent"
    template = "{{ if .Error }}{{ .Error }}{{ else }} {{ end }}"

  [[blocks.segments]]
    template = "{{ .Path }}"
    foreground = "p:blue"
    background = "transparent"
    type = "path"
    style="plain"

    [blocks.segments.properties]
      style = "folder"

  [[blocks.segments]]
    template = " {{ .HEAD }}"
    type = "git"
    foreground = "p:yellow"
    background = "transparent"
    style = "plain"

    [blocks.segments.properties]
    
      [blocks.segments.properties.mapped_branches]
        "feature/*" = "󱓞 "

  [[blocks.segments]]
    template = "]"
    foreground = "p:blue"
    background = "transparent"
    type = "text"
    style="plain"

[[blocks]]
  type="prompt"
  alignment="right"

  [[blocks.segments]]
    template = "{{if .Code}}x{{.Code}}{{end}}"
    foreground = "p:red"
    type = "status"
    style = "plain"  

  [[blocks.segments]]
    type = "executiontime"
    alias = "Ext"
    template = " ext {{.FormattedMs}}"
    foreground = "p:sky"
    style = "plain"

    [blocks.segments.properties]
      threshold = 500
      style="dallas"       
    
[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    template = " "
    foreground = "p:sky"
    type = "text"
    style = "plain"

[transient_prompt]
  template = "> "
  foreground = "p:mauve"

